# renovate: datasource=github-releases depName=jdx/mise
min_version = "2026.3.18"

[tools]
"pipx:yamllint" = "1.38.0"
"pipx" = "1.11.1"
actionlint = "1.7.12"
"pipx:checkov" = "3.2.513"
docker-compose = "5.1.1"
dotenv-linter = "4.0.0"
dprint = "0.53.1"
gitleaks = "8.30.1"
lefthook = "2.1.4"
shellcheck = "0.11.0"
shfmt = "3.13.0"
sops = "3.12.2"
trivy = "0.69.3"
yamlfmt = "0.21.0"
zizmor = "1.23.1"
