---
http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-secure-headers"
    chain-no-auth-plex:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-plex-secure-headers"
    chain-no-auth-immich:
      chain:
        middlewares:
          - "middlewares-rate-limit-loose"
          - "middlewares-immich-secure-headers"
    chain-auth-immich:
      chain:
        middlewares:
          - "middlewares-rate-limit-loose"
          - "middlewares-immich-secure-headers"
          - "middlewares-forward-auth"
    chain-no-auth-qbittorrent:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-qbittorrent-secure-headers"
    chain-auth-qbittorrent:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-qbittorrent-secure-headers"
          - "middlewares-forward-auth"
    chain-no-auth-bitwarden:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-bitwarden-secure-headers"
    chain-auth-bitwarden:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-bitwarden-secure-headers"
          - "middlewares-forward-auth"
    chain-auth:
      chain:
        middlewares:
          - "middlewares-rate-limit"
          - "middlewares-secure-headers"
          - "middlewares-forward-auth"
