---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
    container_name: homepage
    env_file:
      - .env # Decrypted from secret.sops.env
      - ../shared/env/tz.env
    depends_on:
      homepage-docker-proxy:
        condition: service_healthy
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=apps.${DOMAINNAME}
    restart: always
    networks:
      - homepage-frontend
      - homepage-backend
    mem_limit: ${MEM_LIMIT:-300m}
    security_opt:
      - no-new-privileges=true
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=homepage-frontend"
      ## HTTP Routers
      - "traefik.http.routers.homepage-rtr.rule=Host(`apps.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

  homepage-docker-proxy:
    image: lscr.io/linuxserver/socket-proxy:version-3.2.14-r0@sha256:56dde3144ef213d2df1ee3d600baad521bd8b8c2bf844672719b07363606f4c2
    container_name: homepage-docker-proxy
    env_file:
      - ../shared/env/tz.env
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - POST=0 # Disallow any POST operations (effectively read-only)
    restart: always
    networks:
      - homepage-backend
    mem_limit: ${PROXY_MEM_LIMIT:-50m}
    security_opt:
      - no-new-privileges=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true
    tmpfs:
      - /run
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:2375/_ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  homepage-frontend:
    name: homepage-frontend
    driver: bridge
  homepage-backend:
    name: homepage-backend
    driver: bridge
    internal: true
