\getenv app_password OPEN_ARCHIVER_DB_PASSWORD
CREATE ROLE openarchiver LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'app_password';
ALTER DATABASE openarchiver OWNER TO openarchiver;
REVOKE ALL ON DATABASE openarchiver FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO openarchiver;
