---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

# Inspiration: https://technotim.live/posts/homepage-dashboard/

- Homelab:
    - Homelab Docs:
        - abbr: Docs
          icon: si-materialformkdocs-#e5e7eb
          href: https://homelab.devsecninja.com/
    - GitHub Repository:
        - abbr: GH
          icon: si-github-#e5e7eb
          href: https://github.com/DevSecNinja/truenas-apps
    - Renovate Dashboard:
        - abbr: Reno
          icon: si-renovatebot
          href: https://github.com/DevSecNinja/truenas-apps/issues/3
    - Renovate Jobs:
        - icon: si-renovatebot
          href: https://developer.mend.io/github/DevSecNinja/truenas-apps
    - Grafana Cloud Dashboard:
        - icon: si-grafana
          href: https://grafana.com/

- Tools:
    - Speedtest:
        - href: https://speed.cloudflare.com
          icon: cloudflare
    - Photopea:
        - icon: si-photopea-#e5e7eb
          href: https://www.photopea.com/
    - Cronjob Schedule Maker:
        - icon: mdi-clock-outline-#e5e7eb
          href: https://crontab.guru/
    - Ad Blocker Tester:
        - href: https://adblock.turtlecute.org/
          icon: si-adblock-#e5e7eb
    - Certificate Search:
        - href: https://crt.sh
          icon: si-letsencrypt-#e5e7eb
    - AdGuard Temporary Email:
        - abbr: temp-mail
          icon: adguard-home.svg
          href: https://adguard.com/en/adguard-temp-mail/overview.html
    - Typing Club:
        - icon: mdi-keyboard-outline-#e5e7eb
          href: https://www.typingclub.com/
    - Typing Test:
        - icon: mdi-keyboard-outline-#e5e7eb
          href: https://typingtest.now/
    - Monkey Type:
        - icon: mdi-keyboard-outline-#e5e7eb
          href: https://monkeytype.com/
