---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure:
    - NAS:
        href: https://svlnas.{{HOMEPAGE_VAR_DOMAINNAME}}
        icon: truenas
        description: TrueNAS Scale
        siteMonitor: https://svlnas.{{HOMEPAGE_VAR_DOMAINNAME}}
    - JetKVM:
        href: http://jetkvm.MANAGEMENT
        icon: jetkvm
        description: KVM Server
        siteMonitor: http://jetkvm.MANAGEMENT

- IoT:
