---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure:
    - JetKVM:
        href: http://jetkvm.MANAGEMENT
        icon: jetkvm
        description: KVM Server
        siteMonitor: http://jetkvm.MANAGEMENT
