---
services:
  echo-server:
    image: mendhak/http-https-echo:40@sha256:d072446da821a767d05dc19fa5ab6a27b1150bfb5c6ecfaecf3a2e5f9812794c
    container_name: echo-server
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
    restart: always
    ports:
      - 9080:443
    mem_limit: 1024m
    security_opt:
      - no-new-privileges=true
    # No Healthcheck possible since curl is not available in image
