---
services:
  echo-server:
    image: docker.io/mendhak/http-https-echo:40@sha256:d072446da821a767d05dc19fa5ab6a27b1150bfb5c6ecfaecf3a2e5f9812794c
    container_name: echo-server
    env_file:
      - path: .env # Decrypted from secret.sops.env
        required: false
      - path: ../shared/env/tz.env
    user: "3104:3104" # svc-app-echo
    environment:
      - HTTP_PORT=${HTTP_PORT:-80}
      - HTTPS_PORT=${HTTPS_PORT:-443}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - echo-server-frontend
    mem_limit: ${MEM_LIMIT:-1024m}
    pids_limit: 100
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    labels:
      # Homepage
      - homepage.group=Infrastructure
      - homepage.name=Echo-Server
      - homepage.icon=mdi-test-tube-#ffffff
      - homepage.href=https://echo.$DOMAINNAME
      - homepage.description=Testing Web Requests
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=echo-server-frontend"
      ## HTTP Routers
      - "traefik.http.routers.echo-server-rtr.rule=Host(`echo.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.echo-server-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.echo-server-rtr.service=echo-server"
      ### Enable the server port
      - "traefik.http.services.echo-server.loadbalancer.server.port=${HTTP_PORT:-80}"
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--spider"
        - "-q"
        - "http://localhost:${HTTP_PORT:-80}"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  echo-server-frontend:
    name: echo-server-frontend
    driver: bridge
