---
name: Assign issue to CODEOWNERS

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue number to assign (leave empty for all open issues)"
        required: false
        type: number
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  assign:
    uses: DevSecNinja/.github/.github/workflows/assign-issue-to-codeowners.yml@d70256f00b8cd2fabca5d80abe0621e010111eb6 # main
    with:
      issue-number: ${{ inputs.issue-number }}
    permissions:
      contents: read
      issues: write
