---
name: Assign issue to CODEOWNERS

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue number to assign (leave empty for all open issues)"
        required: false
        type: number
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  assign:
    uses: DevSecNinja/.github/.github/workflows/assign-issue-to-codeowners.yml@232d4c32075363b5bd7f090f3adc43cfd275f877 # main
    with:
      issue-number: ${{ inputs.issue-number }}
    permissions:
      contents: read
      issues: write
