---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@1cc371b697c812683b878d0e2201bb1f65718424 # main
    permissions:
      contents: write
      pull-requests: write
