---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  label-sync:
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@9d70999b12a121517fcc40c0e3839479b9bd7b49 # main
    permissions:
      contents: read
      issues: write
