---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@76bb084c3dd335be7cc5cfffead44376120eb68c # main
    permissions:
      contents: read
      pull-requests: write
