---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@57ab8ec508bdf5f3e5f17f22b6ee154137ee42ac # main
    permissions:
      contents: read
      pull-requests: write
