---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  label-sync:
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@57ab8ec508bdf5f3e5f17f22b6ee154137ee42ac # main
    permissions:
      contents: read
      issues: write
