---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  label-sync:
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@e744bc05bb096d6356cc913900ff62482e656046 # main
    permissions:
      contents: read
      issues: write
