---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@e744bc05bb096d6356cc913900ff62482e656046 # main
    permissions:
      contents: read
      pull-requests: write
