---
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  yamlfmt:
    name: yamlfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          install: true
          # renovate: datasource=github-releases depName=jdx/mise
          version: 2026.3.10

      - name: Check YAML formatting
        run: find . -name '*.yaml' -o -name '*.yml' | xargs mise exec -- yamlfmt -lint

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          install: true
          # renovate: datasource=github-releases depName=jdx/mise
          version: 2026.3.10

      - name: Run shellcheck
        run: find . -name '*.sh' | xargs mise exec -- shellcheck
