---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    uses: DevSecNinja/.github/.github/workflows/release.yml@9d70999b12a121517fcc40c0e3839479b9bd7b49 # main
    permissions:
      contents: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.4.3"
      tag: ${{ github.ref_name }}
