---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    uses: DevSecNinja/.github/.github/workflows/release.yml@57ab8ec508bdf5f3e5f17f22b6ee154137ee42ac # main
    permissions:
      contents: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.4.3"
      tag: ${{ github.ref_name }}
