---
name: TODO to Issue

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  run:
    uses: DevSecNinja/.github/.github/workflows/todo-to-issue.yml@9d70999b12a121517fcc40c0e3839479b9bd7b49 # main
    permissions:
      contents: read
      issues: write
