---
name: TODO to Issue

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  run:
    uses: DevSecNinja/.github/.github/workflows/todo-to-issue.yml@76bb084c3dd335be7cc5cfffead44376120eb68c # main
    permissions:
      contents: read
      issues: write
