---
name: TODO to Issue

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  run:
    uses: DevSecNinja/.github/.github/workflows/todo-to-issue.yml@57ab8ec508bdf5f3e5f17f22b6ee154137ee42ac # main
    permissions:
      contents: read
      issues: write
